PROGRAM SAPMZRAILWAY_SAUH1.
TABLES: ZRAILWAY_USER,ZRAILWAY_LOCO,ZRAILWAY_TRAIN,ZRAILWAY_PASS,ZRAILWAY_NOTE.
DATA: wa_user TYPE zrailway_user,
      WA_LOCO TYPE ZRAILWAY_LOCO,
      WA_TRAIN TYPE ZRAILWAY_TRAIN,
      WA_PASS TYPE ZRAILWAY_PASS.
